export const Permissions = {
  ADMIN_PRIVILEGE : 'ADMIN_PRIVILEGE',
  DASHBOARD_LOGIN : 'DASHBOARD_ACCESS',

  USER_FIND : 'USER_FIND',
  USER_COUNT : 'USER_COUNT',
  USER_CREATE : 'USER_CREATE',
  USER_UPDATE : 'USER_UPDATE',
  USER_DELETE : 'USER_DELETE',


};
